// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8g3o9u4lPpKrK4xFWjYoq5fsaUZKHn0U',
    appId: '1:331013861127:android:8a48b0dbd9081712d95fa2',
    messagingSenderId: '331013861127',
    projectId: 'samadhantra-firbase',
    storageBucket: 'samadhantra-firbase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkNteeM9mpMzUvFp7nj5WQZrRxdZZ7sh8',
    appId: '1:331013861127:ios:5c02f5c18f626f29d95fa2',
    messagingSenderId: '331013861127',
    projectId: 'samadhantra-firbase',
    storageBucket: 'samadhantra-firbase.firebasestorage.app',
    iosBundleId: 'com.app.samadhantra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkNteeM9mpMzUvFp7nj5WQZrRxdZZ7sh8',
    appId: '1:331013861127:ios:5c02f5c18f626f29d95fa2',
    messagingSenderId: '331013861127',
    projectId: 'samadhantra-firbase',
    storageBucket: 'samadhantra-firbase.firebasestorage.app',
    iosBundleId: 'com.app.samadhantra',
  );
}
